# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memu
  pod 'SwiftyJSON'
pod 'SDWebImage', '~> 4.3.3'
pod 'Firebase/Messaging'
pod 'SwiftGifOrigin'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'NSObject+Rx'
  pod 'RxAlamofire' , '~> 5.1.0'
  pod 'KeychainAccess'
  pod 'SwiftLocation'
pod 'DropDown'
pod 'MaterialComponents'
    pod 'GooglePlacesSearchController'
  pod 'GooglePlaces'
pod 'MapboxNavigation', '~> 0.40.0'
pod 'IQKeyboardManagerSwift'

 
end
