# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memu
  pod 'SwiftyJSON'
pod 'SDWebImage', '~> 4.3.3'
pod 'MapboxNavigation', '~> 0.40.0'
pod 'Firebase/Messaging'

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'NSObject+Rx'
  pod 'RxAlamofire' , '~> 5.1.0'
  pod 'KeychainAccess'
  pod 'SwiftLocation'
pod 'WWCalendarTimeSelector'
pod 'DropDown'
    pod 'GooglePlacesSearchController'
  pod 'GooglePlaces'
pod 'MapboxNavigation', '~> 0.40.0'
#pod 'MapboxCoreNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v1.0.0-alpha.1'
#pod 'MapboxNavigation', :git => 'https://github.com/mapbox/mapbox-navigation-ios.git', :tag => 'v1.0.0-alpha.1'

 
end
